### ISSUE TITLE
Autoportal into Life challenge?

### ISSUE THREAD

**Issue by Halko-Proude** [genbtc/AutoTrimps#102]
Can this be implemented sometime soon? It's a repeatable challenge and would like to be able to autoportal into it instead of manually each time. Definitely will help early/mid game players too.

**Comment by genbtc** [comment]
Yes. Stay Posted.

**Comment by cLearBody03** [comment]
Have you coded this already genbtc? Can I try to implement this?

**Comment by genbtc** [comment]
nope, go ahead.

**Comment by cLearBody03** [comment]
Code has been updated.
@Halko-Proude is it reflected properly?

**Comment by Halko-Proude** [comment]
Yes it has. Sorry I stopped playing Trimps not too long after posting this
