### ISSUE TITLE
Suggestion for changes to GU options

### ISSUE THREAD

**Issue by ghost** [genbtc/AutoTrimps#131]
At present, the GU options are a bit sparse, and not much of an improvement over the vanilla AutoGolden. For Golden Helium (GH) and Golden Battle (GB), the settings are simple, but for Golden Void (GV), the two options already present just don't make very much sense. Alternating GH and GB, or buying a set number of one or the other after GV is maxed out is an inefficient use of a limited number of GU.

The ideal situation would be a GUI allowing customisation of each individual GU (a table of maybe 25 or so GU, with a second column with a dropdown in each row).
Example: 
GU1 - (GH/GB/GV)
GU2 - (GH/GB/GV)
GU3 - (GH/GB/GV)

The next best option would be to add an option to the GV choice that would buy upgrades as follows:
GU1 - (GV)2%
GU2 - (GV)4% (Cumulative: 6)
GU3 - (GV)6% (Cumulative: 12)
GU4 - (GV)8% (Cumulative: 20)
GU5 - (GV)10% (Cumulative: 30)
GU6 - (**GH**)6%
GU7 - (GV)14% (Cumulative: 44)
GU8 - (GV)16% (Cumulative: 60)
GU9+ Buy GH

This would result in a total of 60% GV bonus, and 6% GH bonus by GU8, which for a player with 3 bonus GU, would be at Zone 125, leaving over 300 zones of extra GV drops to benefit from, with a loss of only a small % of He bonus, which is insignificant in the early zones anyway.

**Comment by genbtc** [comment]
If you want to work on this , I can assign it to you. I'd rather the 2nd choice. What i dont get is why GU6 would buy the helium then, you gotta remember this has to be for all players. It should be ok enough to just buy Voids first then switch over at some point to Helium. The less checkboxes the better.

**Comment by ghost** [comment]
The cap on GV is set at 60%, if you just spam buy voids first that gets you to 56% bonus. Not sure 4% is worth wasting time on though. Buying GH as upgrade 6 means that you miss out the 12% GV upgrade, and instead by the 8th upgrade which is worth 16%, covering that 4%.

 If I knew how to work on it I would, but my knowledge of code just about extends to reading and understanding it I'm afraid.

**Comment by Nydaleclya** [comment]
The 4% are not worth it. For now getting 56% early is better than 60% later. But the moment you have 8 extra GU through achievements it will be worth.

**Comment by genbtc** [comment]
I have pushed a new update to Auto Golden Updates and it now has a new mode called "Max after Helium" that is available under the "Void" dropdown. I am pretty sure it works. It should get the first 30%, then skip 12% and get 14+16=30 = 60%
