### ISSUE TITLE
Equiptment Upgrade

### ISSUE THREAD

**Issue by molekylspektroskopi** [genbtc/AutoTrimps#144]
Not an issue really, more a suggestion/question.

Is it possible to add a setting where it does not always upgrade the equipment from early zones. 
I have a max 200 levels for gear and even though the metal used is not really that massive it is not really necessary to try to upgrade to level 200 almost every time a prestige drop from Blacksmithery III.

Like, don't upgrade gear before zone X

**Comment by JamesBanana** [comment]
Or even better, only upgrade weapons if more damage is useful

**Comment by genbtc** [comment]
set a lower cap than 200. thats against how it was designed. i didnt know people were doing this and i will try to take it into account.

**Comment by genbtc** [comment]
I have taken your feedback and others into account, and pushed a new change that will mean the Liquified and heavily Overkilled zones (under 25 seconds) will behave as 1/10th of your cap. So 200 = 20. 

Additionally I have pushed another change so zones above "Max Map Bonus after Zone" setting will cause Armor to level up to your cap. (and not just sit on 2 )
