### ISSUE TITLE
Info about AutoTrimps AFK in Speed Achieves description

### ISSUE THREAD

**Issue by KilSys** [genbtc/AutoTrimps#148]
![image](https://user-images.githubusercontent.com/22427005/37869526-f3666620-2fc9-11e8-9b4a-8d323a007c09.png)

**Comment by genbtc** [comment]
Darn. I was wondering if this would show up anywhere else :( 
We cant have the hint message at all then, cant work around how i had to shove it in the game.
(in that tooltip anyway)

**Comment by KilSys** [comment]
I guess that info appears after I have clicked "Go AFK Mode" button in "Display" AutoTrimps

**Comment by SinRopa** [comment]
Can you read the contents of the box first, then use a condition to hide it?

**Comment by KilSys** [comment]
It seems that problem is in function formatMinutesForDescriptions() in modules/utils.js . 
I guess, it was planned to use it only in "World Info" box. As far as I understood, it's used not only in World Info but also in description for speed achievements

**Comment by genbtc** [comment]
That is a game function I overwrote to be able to show the seconds. I dont want to start controlling too many game functions. And if I did it outside it would require DOM check and insertion 10x a second leading to performance degradation, So the message will be removed. 13f6148cee4bb30266de868907fccab1132e842d
