### ISSUE TITLE
AutoTrimps fails to start up with console error

### ISSUE THREAD

**Issue by Patashu** [genbtc/AutoTrimps#153]
As of this update

https://github.com/genbtc/AutoTrimps/commit/6ffb358532e7c5b8eb5c04d54ebeccbe569fba73

AT will not start up for me. Using this bookmarklet

```
javascript:with(document)(head.appendChild(createElement('script')).src='https://genbtc.github.io/AutoTrimps/AutoTrimps2.js')._|
```

I get this error

```
Uncaught TypeError: Cannot read property 'src' of null
    at AutoTrimps2.js:27
```

corresponding to this line

```
if (atscript.src.includes('localhost')) {;};
```

If I comment that line out, everything works again.

So add a null check or something, idk.

**Comment by Patashu** [comment]
Also whatever changed in the 'Allocate Perks' functionality totally broke it. I finished a daily and I set my ratio preset to custom, put in the numbers, and hit Allocate Perks, and instead of allocating helium to perks it changes the numbers for my settings. What's going on?

EDIT: It looks like you have also noticed it's broken :D

**Comment by jwelshinger** [comment]
Could fix it like this:

if (atscript && atscript.src.includes('localhost')) {;};

**Comment by genbtc** [comment]
sorry. i figured everyone was using the userscripts for tampermonkey. i commented the line out. 

i reverted autoperks to what it used to be. But It had bugs since always and I was trying to fix them and it did not go well.

**Comment by Patashu** [comment]
Thanks for the fix!
