### ISSUE TITLE
Autoportal is Broken

### ISSUE THREAD

**Issue by Day-Elven** [genbtc/AutoTrimps#19]
http://screenshotlink.ru/v3654/226/OFO0xfJecZo.png
It is set to He/Hr 1% but it does not portal as before.

P.S. Custom portal mode doesn't work too. There are strange messages in the log. Endless starting zone???
http://pp.screenshotlink.ru/v3654/22b/kyhxnocyY8o.png
It seems I have to portal manually now =(

**Comment by Day-Elven** [comment]
Wow, just noticed. A graph that shows dark essence. It seems it reflects endless zone starting bug.
http://pp.screenshotlink.ru/v3654/240/p5JDFd8NHJ0.png
Actually I didn't reach so high zone of course, you can see my true current zone on screenshot from previous message. It seems that this bug appears when game tries to portal and fails.

**Comment by genbtc** [comment]
refresh often.

Bug in magmite spender broke autoportal. Change high level Magma Auto…  …
genbtc committed 6 hours ago 

Autoportal is Broken #19
 Open	Day-Elven opened this issue 4 hours ago ·
