### ISSUE TITLE
Nullifium disappearing...?

### ISSUE THREAD

**Issue by AdsmHorsfield** [genbtc/AutoTrimps#191]
I've just started running AutoTrimps for the first time in the past few days and I've notices that my Nullifium is gradually going down... I started with ~20m but it crept all the way down to ~14k. It's way beyond the stage of my equipped heirlooms having more invested in their stats than is available to spend.

**Comment by genbtc** [comment]
I am not currently the developer anymore. If you are using this verison of the code it is outdated.
Check out the last known current repository @ https://github.com/Zorn192/AutoTrimps
Sorry I thought I put a link in the README saying as much but I dont even see it now myself :P
