### ISSUE TITLE
AutoTrimpicide kills off Titimp for minimal Anticipation stack gain

### ISSUE THREAD

**Issue by CrookedRain** [genbtc/AutoTrimps#23]
I've noticed that the Auto Force-Abandon setting will AutoTrimpicide on maps for minimal Anticipation stack gains while Titimp is active which can end up lowering damage output. In my case, I noticed that it would constantly kill off Titimp for a single stack of Anticipation. I'm not sure what the optimal setting would be for when to AutoTrimpicide, but I would imagine it's not worth it for 1 or 2 stacks. Maybe someone else could chime in with the math on this one.

**Comment by genbtc** [comment]
5 stacks of difference is 1 titimp. good call

**Comment by genbtc** [comment]
I think this is fixed now.
