### ISSUE TITLE
Auto Maps does not trigger properly.

### ISSUE THREAD

**Issue by ShamanBondFPV** [genbtc/AutoTrimps#26]
I have refreshed as of 2016-11-29 at 9:30AM CST, and checked the commits.

The issue is that ever since V4 and Magma the Auto Maps function does not properly trigger when progress is stalled in a zone after Magma shows up.

This happens around Zone 262, then again at 278, 286, etc. AT never switches to maps to get new equipment or farm metal. 

Trimp groups are getting insta-gibbed without damaging the enemy at all, so there's no progress. Switching off Auto Maps and generating a new map to run for about 10 cycles lets me continue. Turning Auto Maps back on results in the same stall behavior.

Auto Maps triggers fine in earlier zones, there's something about zone 230+ that causes it to fail. Is there a check for how long the game has been on a particular zone cell that might trigger Auto Maps to jump in?

**Comment by genbtc** [comment]
From what I can tell you are getting bottlenecked by the new content and automaps isnt triggering, even though it has both enoughHealth and enoughDamage calculations. The only way this could happen is if you are forcing S-stance on. I would suggest putting "Max zone for S stance" at z230 or whatever level you start crapping out at, and using "use when Overkill only" function of S stance from there on out. That way it can auto-swap stances back to where the calculation can be triggered again. Also, I would suggest investing way more into HP from perks, 4.0 is different. 

Additionally, as of 19 hours ago (oddly, unrelated to 1 hour after you made this post) I have changed the enoughHealth calculation to be "survive 8 hits in D stance" from "survive 30 hits in H stance".
Also, dailys are not accounted for yet. (coming soon)
I will consider further work on the automaps calculations

**Comment by ShamanBondFPV** [comment]
I adjusted my Scryer Min Zone up to 270, use when overkill was already on. I adjusted my perk profile to ZXV 3 to see what it does, hopefully that'll clear the issue up.

Ah, that would make sense. Thanks for the update.

**Comment by genbtc** [comment]
Max zone, not min zone.  Max zone means scryer will shut off at that zone (except if you can overkill). Min zone means it won't turn on UNTIL 270, and when it does, it will be FORCED on (and messing up the automap calculations that sadly have no clue about scryer and expect you to be able to handle your scryer formation choices).  That said, I can intuit you are trying to achieve something in between the lines of what I said.  You want scryer to be on for your high level 270-286 for the most profitable dark essence, but also not mess up automapping during that point. I Will attempt to upload a fix that does this later today.

In the meantime, the 4.0 content with magmated scryer essence means that (for example:) you get about the same DE going to 250 as you would going to 280 before. Check your dark essence graph to see the exponential rise and help determine your scryer strategy

**Comment by ShamanBondFPV** [comment]
Yeah, I've noticed that. I adjusted the settings to compensate. I'm waiting for it to run back to 260 to see if it passes without issue.

**Comment by genbtc** [comment]
Also now that I think about it. You were probably stuck on a fast enemy, and there was a recent patch to Trimps (within the last 24 hours) to fix a bug where corrupted enemies were not being calculated as Fast. Now they are, and the game is harder because of it. So im going to add a check to automaps to make sure that you dont get stuck on those either. In addition to putting a calculation in if Scryer wants to be active. Should be done soon.

**Comment by ShamanBondFPV** [comment]
It's normally a Corrupted Snimp or a Corrupted Gorillimp. It's functioning well now with the adjusted settings.
