### ISSUE TITLE
AutoFight: BAF1 #2, breed <= 0.5s x10

### ISSUE THREAD

**Issue by alaendil** [genbtc/AutoTrimps#27]
This issue seems to be related to AutoMaps being on or not.  If I turn AutoMaps off, it runs smoothly. If I turn it on, the script will basically repeat this starting on cell 70 and then moves to 75 after a few sets of failures and enters a loop.

So far I'm up at zone 155 of a new run, so I don't know if AutoMaps will have conflicts when I start needing to run maps (I have BS1 and Hyperspeed2 through Z154 and BS2 to Z231)

 17:18:44 AutoFight: BAF1 #2, breed <= 0.5s x10
 17:18:44 Waiting to travel until your soldiers are finished.
 17:18:44 Waiting to travel until your soldiers are finished.
 17:18:44 Waiting to travel until your soldiers are finished.
 17:18:44 Waiting to travel until your soldiers are finished.

--------------------
I got to 166 as I was typing this up and noticed that the issue has a new debug message
This one popped up
AutoFight: NEW: BAF2 #3, RemainingTime + ArmyAdd.Time < GeneTimer
It's still happening in the same area

edit:
Z177 this popped up quick before moving back to BAF2 #3 
 AutoFight: NEW: BAF2 #4, NextGroupBreedTimer went over 31 and we arent fighting.

after 181 it seems fine, maybe related to running Lead to finish an achievement?  Possible, but seems odd still.

**Comment by alaendil** [comment]
This doesn't appear to be happening with the most recent commit .... Predictive bug fixes are the best bug fixes :)

**Comment by genbtc** [comment]
Refresh again. I found a broken parentheses. Was tempermental.
