### ISSUE TITLE
Inefficient farming?

### ISSUE THREAD

**Issue by LucidCrux** [genbtc/AutoTrimps#28]
Tried this out for a little while today, and I noticed that it tries to always farm on your current world level even when that is not the best way. Even after you hit ten stacks, it continues when it would make more sense to switch to the highest level map with one shots (or overkills). Is there some reason this isn't the case?

Edit: I should probably add that this is still quite early game before even breaking the world.

**Comment by genbtc** [comment]
You're right.

**Comment by genbtc** [comment]
Here, I posted a patch eee960e5ba7c020484f204d0d3d8a49f9f14aaf0 with a new feature.

Add a farm lower level zones option. (in maps settings tab). It does what you said. Although if you are in this situation, waiting for farming to complete at all may be an exercise in futility, and I will continue to look for a way to determine which is better, farming or just plodding along through slow zones. Really neither is a good option, AutoTrimps was made for fast speedruns, and if this ever comes up, you are way past the zone you should portal at. Thats why it was never implemented. But it is now.

Also, once you hit level 110 or 125, you will get a Siphonology perk which did ALREADY do this (thats what the dynamic siphonology option is), except the perk only works down to 3 levels below current zone. So people use that, thats been in the script for a while.

**Comment by LucidCrux** [comment]
Groovy. I only encountered it once that I noticed, I had to set up a situation deliberately to make sure it was happening.

And yeah, this is for speed runs, but since there is already a big base, putting in some general automation stuff in here instead of starting over seemed the better idea. I may start contributing a little bit depending on time. In other words, if I make some more issues that you want to ignore because they don't fit the speedrun idea specifically, feel free. I might get around to them.

**Comment by LucidCrux** [comment]
I did a push run and had this kick in. It does work, but I think there may be a tiny error. It ran one too many maps at world level for whatever reason. I was on 10 bonus and it did one more run before dropping down. It is a minor issue, maybe even a fluke (I'll push another world level to see), and not worth a lot of work or anything, but I thought I would note it.

Edit: Eh, I missed seeing if it did the extra or not.

**Comment by LucidCrux** [comment]
I did another push and tried to catch this, but I missed again. :P Oh well. I think it is at least much improved and usable earlier game.
