### ISSUE TITLE
Better enoughHealth Check

### ISSUE THREAD

**Issue by LucidCrux** [genbtc/AutoTrimps#30]
Currently there is a static check:
enoughHealth = (baseHealth/2 > 8 * (enemyDamage - baseBlock/2 > 0 ? enemyDamage - baseBlock/2 : enemyDamage * pierceMod));

(Which, why is baseBlock divided by 2 by the way? You get full block each time without pierce, right?)

I propose a fix, at least for early game. I don't know how it would work later game. Too tired for specific code and looking up variables, but basically:
enoughHealth = (old stuff) || ( health/2 > enemyDamage - block && 0 < health - (enemyDamage - block) * (repoptime / roundspeed) )

It's late, so I'm not sure that is correct and it doesn't include pierce. The new bit in words is meant to be: make sure we can survive at least one attack, and that the time it takes to repop is less than the time it would take a maxdamage enemy to wipe out our health completely. The current one seems hard coded to require surviving 8 attacks, which seems arbitrary. So the result should be you pass if you have enough to survive 8 attacks, OR you can fully repop before dying.

The reason for this is that at lower levels with extremely fast repop, the health check can still fail when it really shouldn't causing automap to go full bonus despite the fact it is much faster to just keep dying over and over because you can repop the army near instantly and lose no time waiting for respawn. I did a test manually canceling automap from 15 to 25 and saved a bit over an hour (30% time) following that logic.

**Comment by genbtc** [comment]
Baseblock and health /2 is because D stance halves your block and health. I have put in some ifs asking if you have D stance first now: 7098b95db0fda8b73cfa8ca3dfd0b5bd90b7f873
Your proposed fix sounds doable but there is a simpler fix which i can try.

**Comment by genbtc** [comment]
not enough Health doesnt do 10 maps anymore, it only does 1. c32f5c65da3d4b458e9c18ee8dd11a20eb87fd57

This should hold you over.

**Comment by LucidCrux** [comment]
I'm not familiar enough with the how things work to know why that might work. I'll probably see it in action on a run later today. You must enjoy fiddling with this code to respond so quickly.

Is there a reason why just doing a check for 8 hits is used? That is what the code does right? It seems like even in later game speedruns you could run into instances where the repop check would help.

Also, is dominant stance a given once it's unlocked. Sorry if that is a stupid question, I'm not to that point obviously, just trying to understand the code. If not wouldn't a check for that stance work better than just a check for having it unlocked? Or does enoughHealth not get updated whenever a stance might change so it is just erring on the cautious side? I realize that the game has odd mechanics (and autotrimps furthers that) and trying to understand this may be a losing battle without seeing things happen in game and also that I have barely dipped my toes into the code, so feel free to just shoot down anything stupid I say.

**Comment by LucidCrux** [comment]
Hrm, not sure there is a winner here. This did work good for a while, drastically reducing time, but then it got stuck on a map waiting for health. Eventually, it cleared it and even with a pretty big hit to time it was still quite a bit under previous runs, but it just hit another wall on a map.

Not sure how to address that without adding more complicated stuff like checking map clearing ability and if not possible (with some buffer so it doesn't stall on a 1% chance to survive or whatever, which I assume is already the case) farm a bit on a lower map first. : /

I ended up getting around it by hiring a bunch of extra of trainers for now. So maybe it is just a matter of making sure trainers are set up right when doing it. I don't know.

Edit: Actually, considering it again, it might have to do with weird effects from setting the trainer/tribute on. I only had 5 trainers when I stalled and I could very easily afford 40. So, maybe this would work just fine early, but there needs to be an exception in the trainer buying code (which I haven't looked at) to add an exception to purchases before tributes are even available.

Graph of the stall and after I turned of the limiter. http://pasteboard.co/5Vr4sHkt8.png

**Comment by LucidCrux** [comment]
Hrm, I figured out how to include a repop before death check, but in order to avoid repeating the calculations for fullBreed, I'd have to replace breed() to make it accessible since it is local. This is probably a bad thing if the game gets updated and breed() is edited since that would mean the replacement breed() had to get updated as well. Some people frown upon what is basically overwriting a part of the game code, too, even if it is identical except for making local into a global. On the other hand, to get full breading time requires lots of calculations and it would be a hassle to bother adding it since it would require duplicating a bunch of stuff from breed().

Thoughts? I have no idea if the speed increase would have any noticeable effect in the later game. A ways into a later game run, is there much time where repop is still really fast and constantly dying would be a better option than farming bonus or prestige? If it's only pretty early game where it will make a difference, then it's probably not worth the complexity.

**Comment by genbtc** [comment]
D stance is a given. Even if you arent in D stance, you dont want swapping stances to dump you into a map.  8 hits is arbitrary. That area has been recoded for easier reading. 

You need to have your settings correct, Trainers are too important, whatever you did with the "Cap Trainer/tribute" certainly wasnt meant for your level, and I will look into what you said about one being available before the other since to normal level people they are unlocked in the first minute of the game. 

Your replacing breed() isnt necessary, a function exists in AT. getBreedTime() gets the number on the right and getBreedTime(true) gets the number on the left,  in the example of (6.8 secs left / 30 secs).

> is there much time where repop is still really fast and constantly dying would be a better option than farming bonus or prestige

Constantly dying makes sense to me, but not skipping prestiges. This is all very nooby stuff and its going to stop mattering quickly. You are bringing up valid issues but nobody has ever brought them up, they just portal and deal with it.

**Comment by LucidCrux** [comment]
Meh. I have repop check on my fork but where I'm at in game now seems like it will have pretty minimal impact in the long run. Then with the anticipation stuff it seems like you might not even want it to happen. I'll keep looking, because it would be useful for the overzealous trapping too, but the enoughHealth/enoughDamage sections of the code are kind of a mess right now and might need cleaned up first, which might not be a better first task for me anyways. I also don't have a testing environment set up yet to test before a pull request.
