### ISSUE TITLE
Update on AT layout - Graphs

### ISSUE THREAD

**Issue by darkniko** [genbtc/AutoTrimps#32]
A recent upgrade made my AT to block the entire screen when pressing on Graphs. Its like some text was added at the bottom of the opened Tab window and now it covers all the AT menu options. So i can't close it to return to the game. So the only way for me to fix this is to resize the screen so i can see the menu options.

Any tips for me to fix this? Because before this didn't happen and now having to resize it kind of bothers a bit..

http://imgur.com/hqw3ocZ

http://imgur.com/mZQTNlI

http://imgur.com/Zi5HtjQ

The resolution i always use to play the game
![1](https://cloud.githubusercontent.com/assets/24360651/20879524/069be252-bab3-11e6-8c2c-84b9eef6681d.png)

Here with Graphs Tab opened. Can't see Options Menu
![2](https://cloud.githubusercontent.com/assets/24360651/20879525/069c40b2-bab3-11e6-90e0-36036f76815a.png)

Have to resize the screen so i can fit the AT menu options bar and being able to close the TABs.
![3](https://cloud.githubusercontent.com/assets/24360651/20879526/069d0e02-bab3-11e6-9b3f-6b781ffc9503.png)

**Comment by genbtc** [comment]
Jeez. You've got 2 things working against you. Playing on kongregate puts everything in an IFRAME, and apparently messes up the CSS tags that code for width and height. Then youve got a measly 1280x800 resolution. Play on https://trimps.github.io/# in the meantime until I can work out a fix.

**Comment by genbtc** [comment]
I've updated the HTML and CSS code now, it took several hours. It should be a lot better under all scenarios now.

**Comment by darkniko** [comment]
thank you for keeping in mind early game players.
