### ISSUE TITLE
Need an option for mountain or garden maps

### ISSUE THREAD

**Issue by LucidCrux** [genbtc/AutoTrimps#37]
It seems to be rather debatable if it is better to do metal or garden maps. Once they are unlocked, AT automatically uses garden maps without any player choice.

**Comment by genbtc** [comment]
i predicted you would say this, so refresh and type into console: 
MODULES["automaps"].preferGardens = false;

**Comment by LucidCrux** [comment]
:P Using the console isn't an option, it's a hack. But I guess there are a lot of those module variables. Is that the route you are wanting to go with a lot of stuff instead of having options for them? Or you planning on adding that in later?

**Comment by genbtc** [comment]
this is the route for people like you who want to micromanage everything.
