### ISSUE TITLE
Missing Buffer Option?

### ISSUE THREAD

**Issue by LucidCrux** [genbtc/AutoTrimps#38]
Auto portal tooltip says there is a buffer option in genBTC. I don't see it there, but maybe I'm missing it for some reason.

**Comment by genbtc** [comment]
autoportal has to be set to "Helium per hour" setting, to pick the HE/hr buffer. Picking He/hr will then spawn a 2nd challenge dropdown box, which you can select your challenge from there.

**Comment by LucidCrux** [comment]
Except, I think that could be a problem. The tooltip is a bit misleading making you think to look on the genbtc tab, it also means you can't set a desired buffer before you select it so it might auto portal as the tooltip warns.

**Comment by genbtc** [comment]
Ill update the tooltip and add info about how to Use the pause button

**Comment by LucidCrux** [comment]
Ha. If I annoy you, feel free to tell me bugger off, it's good enough. It's just that people are pretty stupid sometimes and I'm big on UI/UX stuff so I have a tendency to nitpick that area especially.
