### ISSUE TITLE
Stuck in abandon loop with Lead + wanting nurseries

### ISSUE THREAD

**Issue by coderpatsy** [genbtc/AutoTrimps#39]
If I'm following the code correctly (haven't done any actual testing), when you're in Lead challenge and on an odd world zone such that it would want to grab nurseries:

[automaps.js:230](https://github.com/genbtc/AutoTrimps/blob/gh-pages/modules/automaps.js#L230) sets both `shouldDoMaps` and `shouldDoWatchMaps` when it wants to grab nurseries.

[:467](https://github.com/genbtc/AutoTrimps/blob/gh-pages/modules/automaps.js#L467) calls `mapsClicked()` once, setting Abandon trimps state (as normal).

[:472](https://github.com/genbtc/AutoTrimps/blob/gh-pages/modules/automaps.js#L472]) triggers another `mapsClicked()`, killing trimps and going to the map screen.

[:491](https://github.com/genbtc/AutoTrimps/blob/gh-pages/modules/automaps.js#L491]) triggers a third `mapsClicked()`, returning to the world and starting the mess all over again.

Maybe add ` && !shouldDoWatchMaps` to the end of [:470](https://github.com/genbtc/AutoTrimps/blob/gh-pages/modules/automaps.js#L470)?

**Comment by genbtc** [comment]
This sounds right, the question is why has that happened, if the nursery map is set to happen on z60 previously (now z50) ? Thats an even zone, and the world is force-exited before it can go to the next world. Did you notice my new module variables and change it ?

**Comment by coderpatsy** [comment]
I saw those but hadn't changed them. Was thinking of setting the nursery zone to right before the spire to get some geneticists that way.

**Comment by genbtc** [comment]
Well I just ran the Lead challenge up to z50, and in fact it did wait till an Odd zone z51 (past cell 59) to do the Nursery map, except I didnt run into any abandon loop.

**Comment by coderpatsy** [comment]
I'll see if I can get a reproducible case.

**Comment by genbtc** [comment]
Secondly, the spire geneticist thing can be solved by setting Trimps settings to "Keep Fighting" not "Map at Spire". Then you will die, causing genetecists to start buying, then go into a map and it would be wise to set  the "Farm X minutes in spire" to the amount of time it takes to buy all your genetecists, that way you can go back into the Spire, die a 2nd time and spawn all your new health from geneticists. This way you only waste around 1 death, but the ton of health should make up for it.

**Comment by coderpatsy** [comment]
Oh, I do have keep fighting off and farm 1 minute at spire set, and that beats the spire. I was just thinking of weird ways to save that minute of farming.

**Comment by genbtc** [comment]
I wonder if its a needing prestige thing on that level.

**Comment by genbtc** [comment]
Unfortunately I dont think that its prestige. Could it be that you have your voids zone set to like, zone 1 with the run new voids option on ?

**Comment by coderpatsy** [comment]
Run Voids at 302, Run New Voids on, New Voids Until 307. No such luck.

**Comment by genbtc** [comment]
Your original theory sounds correct, I'm now looking for why it works for me rather than why it doesnt work for you. I would like to find out before I fix anything.  Been running Lead up to 51 like 4 times now.

**Comment by genbtc** [comment]
Think ive finally uncovered it. Do you not have Home Detector 2 ?

**Comment by coderpatsy** [comment]
I do not have it.

**Comment by genbtc** [comment]
Found it. The fact that it was working at all was sheer luck. https://puu.sh/sI6k0/94db1524cf.png
The reason is If you have NOT fully bred (time still remaining on breed timer), the 2nd mapsclicked() segment doesnt fire. The reason it wasnt firing for me was because I have Home Detector on level 50 (collectors) which causes the breed time to skyrocket. Similarly when it was on z60, the gigastation did the same thing. (There is usually time on the breed clock then anyway).

**Comment by genbtc** [comment]
The fix has been uploaded. Thanks!

**Comment by coderpatsy** [comment]
Haven't seen any problems with a couple quick tests from that save I posted in discord. Thank you!
