### ISSUE TITLE
[Question] Concerning enoughHealth/Damage

### ISSUE THREAD

**Issue by LucidCrux** [genbtc/AutoTrimps#44]
Is there a reason that the calculations are different between equipment/automap? Refactoring and trying to clean it up is something I'd like to take a shot at, but I don't want to jump ahead and 'spoil' the game for myself trying to learn the intricacies of game effects. I also don't want to create a nightmare testing issue for you or keep asking a ton of questions.

They have different things concerning spire and corruption and toxicity for example, and even calls to different functions for damage numbers. Is it just a result of gradually increasing complexity from compensating for new game mechanics over time, or is complexity from trying to eek out lots of tiny speedrun optimizations that need individual considerations? It seems like they should both just be looking for the same same thing, namely can you survive 8 hits and can you one shot.

**Comment by genbtc** [comment]
Fork the current github repo. Dont work off old changes. Remember what you changed and apply them maunally to the new source. I can't deal with explaining it all, the reasons are all of what you said. Merging them serves no purpose. Automaps purpose is to figure out when to go into a map, so its calculations are different. Equipment has spire, and weird numbers for Lead.  You're not even up to that point yet so the calculations are identical.
If you want to change things you have no idea what they are there for, put a code block of: 
if (!setLucidCrux) { //yourstuff } else { //existingcode } and then set a variable to toggle it on. I can say for sure do not mess with Corruption, Lead, or Spire. If you want to change enoughHealth, do it in both equipment and automaps.

EDIT: And i don't think theres much risk of spoiling content by reading the AT code.

**Comment by genbtc** [comment]
Also stop marking issues on github and come to talk in the discord chat https://discord.gg/s75D2 (and not the general channel )

**Comment by genbtc** [comment]
If you want to change things you have no idea what they are there for, put a code block of: 
if (!setLucidCrux) { //yourstuff } else { //existingcode } and then set a variable to toggle it on. I can say for sure do not mess with Corruption, Lead, or Spire. If you want to change enoughHealth, do it in both equipment and automaps.
