### ISSUE TITLE
Daily Challenage Automation

### ISSUE THREAD

**Issue by Altizar** [genbtc/AutoTrimps#47]
Feature:  A flag on the custom portal to run dailies when the become available.

Logic:
Pre 4.0 every time I ran a daily i would get a fraction of the helium of a normal run and take much longer.
Post 4.0 daily runs seem to earn about 80 to 90% of a normal run right up until they complete then make 3 to 5x more per hour than a base corruption run.

While I don't mind once a day doing an extra portal to switch to run the daily, it seems like a waste of magma for the first run of a new day just not to be able to auto be a daily.

**Comment by genbtc** [comment]
OK, but what do you mean a waste of magma? Are you the one who posted on reddit in this thread? https://www.reddit.com/r/Trimps/comments/5hep5q/critical_suggestion_make_magmite_decay_only_on/

**Comment by Altizar** [comment]
No, not that.

So I am running autoportal on he/hr with corruption.  In order to run a daily I either break a corruption run part way through with a manual portal wasting both time on that run and/or magma or turn off autoportal waiting till its around the normal portal level and running the daily manually.

It would be nice if there was a button like the [auto finsih daily] to [auto run daily] so that when autoportal triggers it checks if the daily is available and if so runs it rather than whatever is set as default challenge.

**Comment by genbtc** [comment]
ok

**Comment by genbtc** [comment]
I added this to the script. Enjoy.
