### ISSUE TITLE
Automaps does not change Repeat for Items/Repeat to 10 to Repeat Forever

### ISSUE THREAD

**Issue by FahadZ** [genbtc/AutoTrimps#52]
If a player turns off Ameans utoMaps/AutoTrimps to farm on his own and does not change the repeat configuration to repeat forever before turning on AutoMaps, AutoTrimps does not correct it. This means that when farming, the player's trimps are taken to the map screen at the end of every map causing them to lose their Titimp bonuses and slowing their farm runs ever so slightly. 

This should be a simple fix for a somewhat significant issue since the Titimp bonus doubles the attack.

**Comment by genbtc** [comment]
AutoMaps did disable the repeat for items. Added this now:
automaps: force turn repeat forever on if farming is allowed.
(therefore, If DisableFarming is on, you are allowed to use repeat to 10)

It was presumed that the user would be smart enough to control this his or her self, but you're right, why assume that ?
