### ISSUE TITLE
automaps damage calculation issues

### ISSUE THREAD

**Issue by ElderThorin** [genbtc/AutoTrimps#54]
1)
ourBaseDamage calculation.  This variable appears to be intended to hold the average damage per hit after calculating in average critical hit damage.  However, the comment and code that have it dividing by 2 are incorrect.  The code prior to dividing by 2 correctly calculates the average damage for a critical hit.  You can  test this fairly easily by putting in simple numbers like assume 25% crit chance, assume 10 base damage, assume 2x multiplier.

The line in question:
`ourBaseDamage = (baseDamage * (1-getPlayerCritChance()) + (baseDamage * getPlayerCritChance() * getPlayerCritDamageMult()))/2;`

Further explanation: 1-getPlayerCritChance() gives the chance that we won't get a crit on a given attack.  multiplying that by the baseDamage gives the portion of average damage that comes from a non-crit.
baseDamage * getPlayerCritChance() * getPlayerCritDamageMult() gives the portion of the average damage that comes from getting a crit.  The two added together give the correct total.  Dividing by 2 just halves our actual average damage.  The comment that indicates we're adding 2 hits together is incorrect.

As a side note, in my local clone I use:
ourBaseDamage = baseDamage + (getPlayerCritChance() * baseDamage * (getPlayerCritDamageMult() - 1));

I find it easier to read this.  Explanation: baseDamage is our actual base damage for one hit (I believe it is calculate accurately.)  Then multiply the baseDamage by the crit multiplier - 1, which serves to gives only the portion of the damage that is due to the crit (ie, it's the same as (baseDamage * getPlayerCritDamageMulti()) - baseDamage. so if base damage is 10 and crit multi is 2, the full damage is 20 and the portion due to the crit is 10.)  Multiply this by the crit chance and we get the average additional damage due to crit.

2)
ourBaseDamage2 is only used in the siphonology calculation, though it could be used in the 'lead' calculation.  This is only really an issue because of the following notes:

Currently, because ourBaseDamage is calculated too low, the siphonology calculation will be off a little - but on the other hand it's arguable whether it should use average damage with crit vs using just base damage, since we're trying to compute whether we can one-shot, and we can only guarantee a one-shot using baseDamage.  So the incorrect division by 2 may actually help this calculation work better currently.  On the other hand, not every enemy has the max health, so an average including crit damage might be ok as it may yield mostly one-shots.  I haven't done any extensive testing here to determine what actually works best as I don't have siphonology yet.

<Removed wrong 'lead' notes>

Side note: Once you have the correct average damage (with crit,) it may make sense to re-evaluate some of the cutoffs and other damage calc sections in automaps further, though I've been running with them with the fixed damage calculation for several days, and things seem to be working fine (but I'm still early game, doing runs to about z80.)

**Comment by genbtc** [comment]
Join discord

**Comment by genbtc** [comment]
1. Right.
2. a. ourBaseDamage2 True but irrelevant. 
   b. True. Good consideration, we'll go without the divide by 2, it should be OK.
3. "Not Bug". You dont run maps on the even zones in lead, 
therefore if you took map bonus into account for the odd zones, you'd run less maps, leading to failing the even zone
SideNote: should be ok.
