### ISSUE TITLE
Additional magma options

### ISSUE THREAD

**Issue by elzibubble** [genbtc/AutoTrimps#65]
I only reached magma recently but... it seems the best way to use the generator, initially, is to gain fuel up to some point then switch to magmite farming. EG when the next coord will take too many ticks to achieve. Please could some strategy be added? Even a simple "Farm magmite at zone:" option would be fantastic.

**Comment by FahadZ** [comment]
At 300 magmite, one can purchase the Hybrid mode which switches from gathering Fuel to Magmite at an ideal rate. The script you are asking for would make the in-game feature obsolete which is unfair to the developer.

**Comment by elzibubble** [comment]
Well, the autofight mode and geneticistassist are also obsolete. I thought the point of Autotrimps was to provide better automation and enable near-optimal AFK play?

The hybrid mode (which I have) also keeps taking fuel forever. I imagine there's a point, maybe 5-10 zones before the end of each run, where it's ideal to switch to pure magmite farming. Especially as the corrupted cells can slow you down so your fuel empties and you're not getting max ticks anymore - though that may be mitigated by the Storage upgrade.

I'll close for now and maybe reopen once I'm more confident in optimal magmite farming strategies.
