### ISSUE TITLE
Chrome hangs and crashes

### ISSUE THREAD

**Issue by Jeff-Walker** [genbtc/AutoTrimps#76]
In the past day or so, I've been having 5-10 second pauses which get worse until chrome crashes. This happens on both computers.

**Comment by krisavi** [comment]
Having the same issues, also memory usage of 1.5Gb seems a bit high for Trimps tab. Will test if Firefox handles it better.

**Comment by Jeff-Walker** [comment]
I turned off "Better Autofight" and it has been stable for a couple of hours.

**Comment by krisavi** [comment]
For me it has been running in firefox from the time of the post without any crashes. With various extensions and plugins firefox is taking 750 MB of memory which is at least a lot less than only trimps chrome tab usage of 1.5GB. For me the same issues started around 3-4 weeks ago. Probably with the trimps version 4.31 and I think some update of the script.

**Comment by Jeff-Walker** [comment]
It looks like this have been fixed. I guess with Trimps 4.31.
