### ISSUE TITLE
Challenge2 Meditate issue

### ISSUE THREAD

**Issue by Mefra85** [genbtc/AutoTrimps#78]
Yesterday I noticed an issue with running the Meditate Challenge2. Instead of using the automaps correctly it kept going back to Trimple of Doom (level 33) and into prestige mode. Proceeded by using manual maps and after portalling into another challenge the whole issue seized to exist.

No idea why this happens. Might be an error from my side or from Autotrimps.

Same thing happens on the Electricity challenge2, but then keeps going back to the Prison (level 80) for prestige...

Turning off "run unique maps" solves the issue...

**Comment by PillowPalita** [comment]
I had the same issue happening to me!

**Comment by genbtc** [comment]
This has since been fixed luckily thanks to some of the kind coders while I was gone.
