### ISSUE TITLE
Ignores -1 for "Minutes to farm before spire"

### ISSUE THREAD

**Issue by wstanulis** [genbtc/AutoTrimps#80]
I put -1 in for the "Minutes to farm before Spire" option.  It shows it as it will farm for infinite time. I hit 200 and started farming the maps, but it stopped farming at went into the spire once the H:D ratio was under 16. I changed it to a very large minutes and it instantly went back to farming the maps.

**Comment by genbtc** [comment]
-1 means infinite man. just like every other place. 0 means 0. read tooltip

**Comment by genbtc** [comment]
if its not that way ill fix it later. been away

**Comment by genbtc** [comment]
Coming back to this, I now realize what you meant.  Unfortunately changing it now would likely break a buncha peoples games un-necessarily, so it will have to be this way for now.
3c269e882bd9ea077a95989f5bd1ea0f973a6b95 = Tooltip updated to reflect that.
