### ISSUE TITLE
Keep researching science instead of trapping and hiring scientists - very low level

### ISSUE THREAD

**Issue by CrustytheClown** [genbtc/AutoTrimps#81]
I have just started a new game and I keep researching even when I have enough science to upgrade each unlocked science one level. This also means that my trimp population hovers around 18, while I have a maximum of around 80. Therefore my production keeps lagging behind and I don't even hire scientists automatically with a population that low. This problem persists with both autofight settings.
Pausing Autotrimps and filling my population up fixes this problem partially.

**Comment by DerSkagg** [comment]
What is your HZE? I am curious if you are running AT in an unsupported way.

**Comment by genbtc** [comment]
Marked as Low level.
