### ISSUE TITLE
Auto Maps issue

### ISSUE THREAD

**Issue by kvoorneveld** [genbtc/AutoTrimps#83]
I've just restarted playing Trimps on Kong. After a few portals I decided to install AutoTrimps, since I have played before and wanted to make life easier a bit. On every portal at level 6 the fighting just stops. No new fight is started after my trimps die. When I deselect Aut Maps, it starts going again. It seems that the scripts wants to start a map, but something goes wrong. It does not enter the map screen or anything.
I have checked this against an old save which has progessed a lot further with the same reult. It happens on both Chrome and Firefox.
It could be that I've just missed a setting that causes this, so I'm not sure if it really is an issue. If so, please let me know.

**Comment by damadorPL** [comment]
too low level maybe ?

**Comment by Orkenschlaechter** [comment]
i have the same problem. automapping does nothing except stoping the autofights. my max zone is z55.
i tried to start auto trimps with greasemonkey, per console and per bookmark in firefox and in chrome and its everywhere the same problem

**Comment by kvoorneveld** [comment]
It's not related to my level. Although it's low on this account I also have another that is at 170+ and it gives the same result.

**Comment by genbtc** [comment]
Reset your autotrimps settings to defaults. Level 6 is where the script
begins to start automapping. Its probably caused by using an outdated
autotrimps settings file that got badly upgraded. So just delete your AT
settings with the button in AT stetings "reset to defaults" and start
configuring it from scratch.

**Comment by Orkenschlaechter** [comment]
that fixed it for me thank you :)

**Comment by kvoorneveld** [comment]
Looks like that was the problem indeed. Thanks a lot!
