### ISSUE TITLE
Install/download link still on 2.1.5.2

### ISSUE THREAD

**Issue by rgreen83** [genbtc/AutoTrimps#84]
Would like to come back to genbtc from uni, but can't since I don't know how to get the newer version (2.1.5.6 currently) supporting uni save format.

**Comment by damadorPL** [comment]
check the source  - it link scritp source to https://genbtc.github.io/AutoTrimps/AutoTrimps2.js

// ==UserScript==
// @name         AutoTrimpsV2+unimod
// @version      2.1.5.6-genbtc-8-26-2017+UniMod

the "loader" have outdated version info but load correct new version

**Comment by genbtc** [comment]
Changed the version of the userscript to match. in commit # ef6e65b89b60956ba61165a8cf5bd4069c6dcd51
