### ISSUE TITLE
Constant error automaps

### ISSUE THREAD

**Issue by thenikolaj** [genbtc/AutoTrimps#86]
automaps.js:90 Uncaught TypeError: Cannot read property 'last' of undefined
    at autoMap (automaps.js:90)
    at mainLoop (AutoTrimps2.js:202)

happens after each reload of http://trimps.github.io/

**Comment by SomeoneIsWorking** [comment]
Set prestige value to anything in AutoTrimps menu > Gear > Prestige

**Comment by genbtc** [comment]
Fixed in commit 8f1effa55fa40081f0c7af2708875cf549228fb3
