### ISSUE TITLE
Default prestige value is "" causing script errors

### ISSUE THREAD

**Issue by SomeoneIsWorking** [genbtc/AutoTrimps#89]
Uncaught TypeError: Cannot read property 'last' of undefined
    at autoMap (automaps.js:90)
    at mainLoop (AutoTrimps2.js:202)

Hundreds of this error because  game.mapUnlocks[prestige].last which resolves to  game.mapUnlocks[""].last => undefined.last => error

**Comment by genbtc** [comment]
Fixed in commit 8f1effa55fa40081f0c7af2708875cf549228fb3
