### ISSUE TITLE
Max Tox Stacks not auto-disabling after successful max-run

### ISSUE THREAD

**Issue by kaeroku** [genbtc/AutoTrimps#92]
Pretty much title. Tooltip for max tox stacks says it will auto-disable if it completes a successful max-stacks run. Did a start-to-finish max stacks run, auto-portaled, but did not disable (started trying to do another max-stacks run.)

I manually disabled it, and it's no big deal, but maybe change the tooltip to inform people they need to manually disable.

**Comment by genbtc** [comment]
Thanks for the bug report. fixed in 4d229c63e83d20dd74444a7c58f2a310d12c3a85
Out of curiosity I tracked it down and the code got lost in a commit  Date:		1 year ago (5/29/2016 11:05:07 PM)
Commit hash:	85c507d63f6192cb5a43c3d60957202270ae50df
