### ISSUE TITLE
buildings.js stops buying food-limited housing when first is maxed

### ISSUE THREAD

**Issue by JamesBanana** [genbtc/AutoTrimps#94]
buildings.js does not check which food-limited housing is the most cost effective non maxed option. This causes all food limited housing to stop building once the first one is maxed.

There is a check for this in gem-limited housing, which can keep building if one or more is already maxed.

**Comment by genbtc** [comment]
This is working as intended. Like this: 
![image](https://user-images.githubusercontent.com/3683744/32861984-8ff6f740-ca24-11e7-88d6-226294763bf1.png)
When you cap to 100. The difference is meaningless. Fix it if you want. It's only an issue at a point when AT isn't intended for, and even then not hugely. The housing is bought according to which OVERALL housing is the most cost-effective option between FoodHousing and FoodGemHousing and GemHousing. Spending more food to achieve optimal food-only housing even though the FoodGem Housing is already cost-effectivity maxed is counter-productive.
Example: In the pic above, Maxing these out to 100 costs:
11 Huts: 4.81e11 food / 2.81e11 wood for 1175 trimps.
14 Houses: 6.68e11 food / 3.34e11 wood / 6.68e10 metal for 1959 trimps.
6 Mansions: 1.24e12 food / 8.26e11 wood / 2.07e11 metal / 4.3e10 gems for 3918 trimps.
**TOTAL: 2.6e12 food / 1.4e12 wood / 2.73e12 metal / 4.3e10 gems for 7052 trimps.**
Compare that to buying the 101th Resort: 
**1.29e11 food / 1.55e11 wood / 6.47e10 metal / 2.59e10 gems. for 15700 trimps.**
The 101th Resort would be WAY more effective, but you have capped to 100.  So it stops. This is desirable.
I would be interested in your rationale? 
The only reason to want this changed i can think of really is "if i look at it its nicer if they are all at 100" - and that does not matter unless you have OCD, in which case you should have specified that.

**Comment by JamesBanana** [comment]
Well, like you stated the biggest reason is that it would look much nicer. I don't actually have OCD, but uneven numbers annoys me slightly. 

I completely understand the reasoning behind this design decision, but the behavior is slightly unpredictable right now. If i for some reason change the settings to max 200 huts and 100 of the rest, it would not give 200 huts which is confusing. In order to end up at 200 huts, i would need to increase all the other buttons which is not logical from a user perspective.

I guess there could be a switch for changing between optimum and nice looking building limits, but that might just bloat the settings UI.
