### ISSUE TITLE
Void Maps being run after Spire attempts instead of before

### ISSUE THREAD

**Issue by Halko-Proude** [genbtc/AutoTrimps#95]
I currently have my AT script to run Void Maps at Z400, and Max Map Bonus for Spire, with the intent to run Void Maps to farm before Spire III. However, the script makes the game farm regular maps instead. Can a setting or fix be implemented to run Voids before Spire?

**Comment by genbtc** [comment]
You should probably be running you voids on an xx5 zone
Or any poison zone - Z400 is ice.
If you join the discord channel you can read the discussion about it https://discord.gg/0VbWe0dxB9kIfV2C
