### ISSUE TITLE
Firefox 57 - Autotrimps not running

### ISSUE THREAD

**Issue by adeleglise** [genbtc/AutoTrimps#96]
I'm using the new Firefow 57 on Ubuntu 17.10.

Greasemonky has been succefully updated to v4. Autotrimps still installed and enabled.

In the game on kongregate, autotrimps is not running, no options at all can be seen in the game screen.

No logs or errors are displayed.

**Comment by genbtc** [comment]
Use Tampermonkey instead to solve this. I have no idea why.

**Comment by adeleglise** [comment]
Ok I confirm that Autotrimps works fine with tampermonkey on Firefox 57/ubuntu 17.10.

Thanks for your answer.
